// Conservative, high-signal path wordlist for exposed-file / misconfig recon.
//
// Deliberately small and non-aggressive: these are common accidental exposures,
// not a brute-force dictionary. Extend via ScanRequest.extraPaths.

export const SENSITIVE_PATHS: string[] = [
  '/.git/config',
  '/.git/HEAD',
  '/.env',
  '/.env.local',
  '/.env.production',
  '/config.json',
  '/config.yml',
  '/.DS_Store',
  '/backup.zip',
  '/backup.sql',
  '/db.sql',
  '/dump.sql',
  '/.aws/credentials',
  '/wp-config.php.bak',
  '/phpinfo.php',
  '/server-status',
  '/.svn/entries',
  '/.htaccess',
  '/.htpasswd',
  '/.npmrc',
  '/.git-credentials',
  '/web.config',
  '/id_rsa',
  '/docker-compose.yml',
  '/robots.txt',
  '/sitemap.xml',
  '/security.txt',
  '/.well-known/security.txt',
  '/swagger.json',
  '/swagger/v1/swagger.json',
  '/swagger/v2/swagger.json',
  '/openapi.json',
  '/openapi.yaml',
  '/v1/openapi.json',
  '/v2/openapi.json',
  '/api/openapi.json',
  '/api/swagger.json',
  '/api-docs',
  '/api-docs/swagger.json',
  '/docs/swagger.json',
  '/swagger-ui/',
  '/swagger-ui/index.html',
  '/redoc',
  '/graphql',
  '/graphql/',
  '/api/graphql',
  '/v1/graphql',
  '/graphiql',
  '/playground',
  '/actuator',
  '/actuator/env',
  '/actuator/health',
  '/actuator/mappings',
  '/metrics',
  '/main.js.map',
  '/app.js.map',
  '/static/js/main.js.map',
];

export const API_PROBE_PATHS: string[] = [
  '/',
  '/api',
  '/api/v1',
  '/api/v2',
  '/login',
  '/admin',
  '/admin/dashboard',
  '/user',
  '/account',
  '/me',
  '/profile',
  '/settings',
  '/dashboard',
  '/api/v1/me',
  '/api/me',
  '/api/v1/user',
  '/api/v1/users/1',
  '/api/v1/users/me',
  '/api/users/1',
  '/users/1',
  '/users/me',
  '/oauth/authorize',
  '/oauth/callback',
  '/oauth/token',
  '/oauth2/authorize',
  '/.well-known/oauth-authorization-server',
];

/** Paths useful for cache-deception follow-up (paired with static suffixes). */
export const CACHE_BAIT_PATHS: string[] = [
  '/account',
  '/me',
  '/profile',
  '/settings',
  '/dashboard',
  '/api/v1/me',
  '/users/me',
];
