// Conservative, high-signal path wordlist for exposed-file / misconfig recon.
//
// Deliberately small and non-aggressive: these are common accidental exposures,
// not a brute-force dictionary. Extend via ScanRequest.extraPaths.

export const SENSITIVE_PATHS: string[] = [
  '/.git/config',
  '/.git/HEAD',
  '/.env',
  '/.env.local',
  '/.env.production',
  '/config.json',
  '/config.yml',
  '/.DS_Store',
  '/backup.zip',
  '/backup.sql',
  '/db.sql',
  '/dump.sql',
  '/.aws/credentials',
  '/wp-config.php.bak',
  '/phpinfo.php',
  '/server-status',
  '/.svn/entries',
  '/.htaccess',
  '/robots.txt',
  '/sitemap.xml',
  '/security.txt',
  '/.well-known/security.txt',
  // OpenAPI / Swagger
  '/swagger.json',
  '/swagger.yaml',
  '/swagger/v1/swagger.json',
  '/swagger/v2/swagger.json',
  '/v2/api-docs',
  '/v3/api-docs',
  '/v3/api-docs.yaml',
  '/api-docs',
  '/api-docs.json',
  '/api/swagger.json',
  '/api/openapi.json',
  '/openapi.json',
  '/openapi.yaml',
  '/openapi.yml',
  '/docs/openapi.json',
  '/swagger-ui/',
  '/swagger-ui/index.html',
  '/swagger-ui.html',
  '/swagger/index.html',
  '/redoc',
  '/redoc/index.html',
  // GraphQL
  '/graphql',
  '/graphql/',
  '/api/graphql',
  '/api/v1/graphql',
  '/v1/graphql',
  '/query',
  '/graphiql',
  '/graphiql/',
  '/playground',
  '/playground/',
  '/altair',
  '/___graphql',
  // Spring / misc admin
  '/actuator',
  '/actuator/env',
  '/actuator/health',
  '/metrics',
];

/**
 * Paths that frequently leak secrets when misconfigured (env files, JS config,
 * cloud credential files). Merged into probe expansion by the scanner.
 */
export const SECRET_LEAK_PATHS: string[] = [
  '/.env',
  '/.env.local',
  '/.env.production',
  '/.env.development',
  '/.env.staging',
  '/.aws/credentials',
  '/credentials.json',
  '/secrets.json',
  '/secret.json',
  '/config.json',
  '/config.yml',
  '/config.yaml',
  '/config.js',
  '/config.env',
  '/env.js',
  '/settings.js',
  '/settings.json',
  '/appsettings.json',
  '/appsettings.Development.json',
  '/appsettings.Production.json',
  '/local.settings.json',
  '/application.properties',
  '/application.yml',
  '/application-prod.yml',
  '/docker-compose.yml',
  '/docker-compose.yaml',
  '/.npmrc',
  '/.netrc',
  '/.dockercfg',
  '/.docker/config.json',
  '/id_rsa',
  '/id_rsa.pub',
  '/wp-config.php',
  '/wp-config.php.bak',
  '/web.config',
  '/firebase.json',
  '/google-services.json',
  '/serviceAccount.json',
  '/service-account.json',
  '/api/config',
  '/api/v1/config',
  '/js/config.js',
  '/static/js/config.js',
  '/assets/config.js',
  '/main.js',
  '/app.js',
];

/** Paths that are strong GraphQL / explorer candidates for introspection follow-up. */
export const GRAPHQL_PATHS: string[] = [
  '/graphql',
  '/graphql/',
  '/api/graphql',
  '/api/v1/graphql',
  '/v1/graphql',
  '/query',
  '/graphiql',
  '/graphiql/',
  '/playground',
  '/playground/',
  '/altair',
  '/___graphql',
];

/** OpenAPI / Swagger documentation paths. */
export const OPENAPI_PATHS: string[] = [
  '/swagger.json',
  '/swagger.yaml',
  '/swagger/v1/swagger.json',
  '/swagger/v2/swagger.json',
  '/v2/api-docs',
  '/v3/api-docs',
  '/v3/api-docs.yaml',
  '/api-docs',
  '/api-docs.json',
  '/api/swagger.json',
  '/api/openapi.json',
  '/openapi.json',
  '/openapi.yaml',
  '/openapi.yml',
  '/docs/openapi.json',
  '/swagger-ui/',
  '/swagger-ui/index.html',
  '/swagger-ui.html',
  '/swagger/index.html',
  '/redoc',
  '/redoc/index.html',
];

// Paths worth probing for CORS / auth behavior (API-ish surfaces).
export const API_PROBE_PATHS: string[] = [
  '/',
  '/api',
  '/api/v1',
  '/api/v2',
  '/api/v3',
  '/login',
  '/admin',
  '/user',
  '/users',
  '/account',
  '/auth',
  '/oauth',
  '/session',
  '/me',
  '/profile',
];

/**
 * High-signal auth / IDOR probe paths with predictable object IDs.
 * Unauthenticated 2xx + sensitive body markers → candidate access-control finding.
 */
export const AUTH_IDOR_PATHS: string[] = [
  '/me',
  '/api/me',
  '/api/v1/me',
  '/api/v1/user',
  '/api/v1/users',
  '/api/v1/users/1',
  '/api/v1/users/me',
  '/api/v1/profile',
  '/api/v1/profile/1',
  '/api/v1/account',
  '/api/v1/accounts/1',
  '/api/v1/orders/1',
  '/api/v1/admin',
  '/api/v1/admin/users',
  '/api/users',
  '/api/users/1',
  '/api/user/1',
  '/api/admin',
  '/api/admin/users',
  '/user/1',
  '/users/1',
  '/users/me',
  '/account/1',
  '/accounts/1',
  '/admin/users',
  '/admin/user/1',
  '/profile/1',
];

/**
 * Auth / token / OTP / password-reset surfaces where missing rate limits
 * enable credential stuffing and online guessing (brute-force).
 */
export const BRUTEFORCE_PATHS: string[] = [
  '/login',
  '/signin',
  '/sign-in',
  '/log-in',
  '/auth',
  '/auth/login',
  '/api/login',
  '/api/auth',
  '/api/auth/login',
  '/api/v1/login',
  '/api/v1/auth',
  '/api/v1/auth/login',
  '/session',
  '/api/session',
  '/oauth/token',
  '/oauth2/token',
  '/token',
  '/api/token',
  '/api/v1/token',
  '/forgot-password',
  '/reset-password',
  '/password/reset',
  '/password/forgot',
  '/api/v1/password/reset',
  '/otp',
  '/api/otp',
  '/api/v1/otp',
  '/mfa',
  '/2fa',
  '/register',
  '/signup',
  '/sign-up',
  '/api/register',
  '/api/v1/register',
];
